#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2017, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)

SRC=$1
DST=$2

VMID=$3
DSID=$4

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)

#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

DST_PATH=`arg_path $DST`
DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

SRC_ARG_PATH=`arg_path $SRC`

DST_DS_PATH="$(dirname $(dirname $(dirname $DST_PATH)))"
SRC_DS_PATH="$(dirname $(dirname $SRC_ARG_PATH))"

SRC_PATH="${DST_DS_PATH}${SRC_ARG_PATH##$SRC_DS_PATH}"

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

DISK_ID=$(basename ${DST_PATH} | cut -d. -f2)

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VMID | $XPATH \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/ORIGINAL_SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/NETAPP_HOST \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/NETAPP_VOLUME \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/NETAPP_PATH \
                    /VM/HISTORY_RECORDS/HISTORY[last\(\)]/TM_MAD)

SIZE="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"
NETAPP_HOST="${XPATH_ELEMENTS[j++]}"
NETAPP_VOLUME="${XPATH_ELEMENTS[j++]}"
NETAPP_PATH="${XPATH_ELEMENTS[j++]}"
TM_MAD="${XPATH_ELEMENTS[j++]}"

if [ "$TM_MAD" = "ssh" ]; then
    MONITOR="ssh"
else
    MONITOR=""
fi

if [ -z "$NETAPP_HOST" -o -z "$NETAPP_PATH" -o -z "$NETAPP_VOLUME" ]; then
    msg="In order to use TM/NetApp you need to add to your datastore"
    msg="$msg NETAPP_PATH, NETAPP_VOLUME and NETAPP_HOST"
    log_error "$msg"
    exit 1
fi

#-------------------------------------------------------------------------------
# Recalculate SRC and DST paths in NetApp
#-------------------------------------------------------------------------------

NETAPP_SRC_PATH=${SRC_PATH/$SRC_DS_PATH\//$NETAPP_PATH/}
NETAPP_DST_PATH=${DST_PATH/$DST_DS_PATH\//$NETAPP_PATH/}

#-------------------------------------------------------------------------------
# Create DST path
#-------------------------------------------------------------------------------

ssh_make_path $DST_HOST $DST_DIR $MONITOR

#-------------------------------------------------------------------------------
# Clone (cp) SRC into DST in NetApp
#-------------------------------------------------------------------------------

log "Cloning $NETAPP_SRC_PATH to $NETAPP_DST_PATH " \
    " in NetApp :$NETAPP_HOST, Volume: $NETAPP_VOLUME "

CLONE_CMD="volume file clone create \
        -volume $NETAPP_VOLUME \
        -source-path $NETAPP_SRC_PATH \
        -destination-path $NETAPP_DST_PATH"

# Clone in NetApp
ssh_exec_and_log "$NETAPP_HOST" \
                 "$CLONE_CMD" \
                 "Error cloning $NETAPP_SRC_PATH to $NETAPP_DST_PATH"

# Resize
if [ -n "$ORIGINAL_SIZE" -a "$SIZE" -gt "$ORIGINAL_SIZE" ]; then
    RESIZE_CMD="qemu-img resize ${DST_PATH} ${SIZE}M"
    ssh_exec_and_log $DST_HOST "$RESIZE_CMD" "Error resizing $DST"
fi

exit 0
